#updating V5 image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/clever-axe-447305-k1/sample-images-repo/simple-python-app1:V9.2', './app1' ]
  id: 'Build Docker Image'
  
  # images::
  # - 'us-central1-docker.pkg.dev/<your_project_id>/gke-repo/quickstart-image-'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/clever-axe-447305-k1/sample-images-repo/simple-python-app1:V9.2' ]
  id: 'Push Docker Image'

#- name: 'gcr.io/cloud-builders/docker'
# args: ['build', '-t', 'us-central1-docker.pkg.dev/<your_project_id>/gke-repo/flask-image', './app2' ]
#id: 'Build Docker Image2'

  # images:
  # - 'us-central1-docker.pkg.dev/<your_project_id>/gke-repo/quickstart-image'

#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'us-central1-docker.pkg.dev/<your_project_id>/gke-repo/flask-image' ]
#  id: 'Push Docker Image2'

#- name: "gcr.io/cloud-builders/gcloud"
#  entrypoint: "bash"
#  waitFor: ["-"]
#  id: "manual-approval"
    
- name: 'google/cloud-sdk:latest'
  id: Deployment Ready
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
    gcloud deploy apply --file deploy/dev.yaml --region=us-central1
    gcloud deploy apply --file deploy/prod.yaml --region=us-central1
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=dev-prod-pipeline --region=us-central1 --skaffold-file=skaffold.yaml


options:
  logging: CLOUD_LOGGING_ONLY
