apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/clever-axe-447305-k1/locations/us-east1-c/clusters/my-prod-cluster

