apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: us-central1-docker.pkg.dev/clever-axe-447305-k1/sample-images-repo/simple-python-app1:V7
          ports:
            - containerPort: 8080
#commit-test
apiVersion: v1
kind: Service
metadata:
  name: my-py-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
